---

storage:
  host: postgres-k121bot-service
  port: 5455
  database: postgres
  username: postgres
  password: postgres
  maxAttempts: 5
telegram:
  token: "5038476456:AAE3pwITMe_EOc1cGiEbsjzHox7TF135Bsk"
