---

storage:
  host: k121bot-do-user-11432745-0.b.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  username: doadmin
  password: AVNS_5cxydjDQT162Mz6
  maxAttempts: 5
telegram:
  token: "5038476456:AAE3pwITMe_EOc1cGiEbsjzHox7TF135Bsk"
