apiVersion: v1
kind: Service
metadata:
  name: k121bot-service
  namespace: {{.Values.namespace}}

spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      protocol: TCP
  type: ClusterIP