image:
  repository: ""
  tag: ""

container:
  port: 80
  targetPort: 8080
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1
namespace: default

config:
  db:
    url: ""
    username: postgres
    password: postgres
    driver_class_name: org.postgresql.Driver
    retries: 5
    baseline: true
