image:
  repository: ""
  tag: ""

container:
  port: 80
  targetPort: 8080
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1
namespace: default

db:
  host:
  url:  # dsn
  name:
  port:
  username:
  password:
  driver_class_name: org.postgresql.Driver
  retries: 5
  baseline: true

telegram:
  token: ""
