image:
  repository: michaellazebny/k121bot
  tag: ""

container:
  port: 80
  targetPort: 8080
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1

config:
  db:
    url: "jdbc:postgresql://postgres-k121bot-service:5455/postgres"
    username: postgres
    password: postgres
    driver_class_name: org.postgresql.Driver
    retries: 5
    baseline: true
